
const PAROISSES = [
  {
    id: 1,
    nom: "Cathédrale Notre-Dame des Victoires",
    ville: "Dakar", quartier: "Plateau",
    adresse: "Avenue Pasteur, Dakar",
    telephone: "+221 33 822 45 67",
    email: "cathedrale.dakar@eglise.catho.sn",
    horaires: {
      dimanche: ["07:00","09:00","11:00","18:00"],
      lundi:    ["07:00","18:30"], mardi:    ["07:00","18:30"],
      mercredi: ["07:00","18:30"], jeudi:    ["07:00","18:30"],
      vendredi: ["07:00","18:30"], samedi:   ["07:00","18:30"]
    },
    coordonnees: { lat: 14.6694, lon: -17.4386 },
    curé: "Père Jean-Marie Diop"
  },
  {
    id: 2,
    nom: "Église Saint-Paul de Thiès",
    ville: "Thiès", quartier: "Centre-ville",
    adresse: "Avenue Lamine Guèye, Thiès",
    telephone: "+221 33 951 23 45",
    email: "stpaul.thies@eglise.catho.sn",
    horaires: {
      dimanche: ["07:00","09:00","11:00","18:00"],
      lundi:    ["07:00","18:30"], mardi:    ["07:00","18:30"],
      mercredi: ["07:00","18:30"], jeudi:    ["07:00","18:30"],
      vendredi: ["07:00","18:30"], samedi:   ["07:00","18:30"]
    },
    coordonnees: { lat: 14.7756, lon: -16.9234 },
    curé: "Père André Faye"
  },
  {
    id: 3,
    nom: "Église Saint-Michel de Kaolack",
    ville: "Kaolack", quartier: "Centre-ville",
    adresse: "Avenue du Général de Gaulle, Kaolack",
    telephone: "+221 33 945 23 45",
    email: "stmichel.kaolack@eglise.catho.sn",
    horaires: {
      dimanche: ["07:00","09:00","11:00","18:00"],
      lundi:    ["07:00","18:30"], mardi:    ["07:00","18:30"],
      mercredi: ["07:00","18:30"], jeudi:    ["07:00","18:30"],
      vendredi: ["07:00","18:30"], samedi:   ["07:00","18:30"]
    },
    coordonnees: { lat: 14.1823, lon: -16.2567 },
    curé: "Père Antoine Sarr"
  },
  {
    id: 4,
    nom: "Église Saint-Pierre de Saint-Louis",
    ville: "Saint-Louis", quartier: "Sud",
    adresse: "Rue de Saint-Louis",
    telephone: "+221 33 962 34 56",
    email: "stpierre.stlouis@eglise.catho.sn",
    horaires: {
      dimanche: ["07:00","09:00","11:00","18:00"],
      lundi:    ["07:00","18:30"], mardi:    ["07:00","18:30"],
      mercredi: ["07:00","18:30"], jeudi:    ["07:00","18:30"],
      vendredi: ["07:00","18:30"], samedi:   ["07:00","18:30"]
    },
    coordonnees: { lat: 16.2345, lon: -16.4567 },
    curé: "Père François Seck"
  },
  {
    id: 5,
    nom: "Église Saint-Paul de Ziguinchor",
    ville: "Ziguinchor", quartier: "Centre-ville",
    adresse: "Avenue de Ziguinchor",
    telephone: "+221 33 976 54 32",
    email: "stpaul.ziguinchor@eglise.catho.sn",
    horaires: {
      dimanche: ["07:00","09:00","11:00","18:00"],
      lundi:    ["07:00","18:30"], mardi:    ["07:00","18:30"],
      mercredi: ["07:00","18:30"], jeudi:    ["07:00","18:30"],
      vendredi: ["07:00","18:30"], samedi:   ["07:00","18:30"]
    },
    coordonnees: { lat: 12.5678, lon: -16.2345 },
    curé: "Père Jean-Baptiste Sène"
  },
  {
    id: 6,
    nom: "Église Saint-Pierre de Kolda",
    ville: "Kolda", quartier: "Centre-ville",
    adresse: "Route de Kolda",
    telephone: "+221 33 912 34 56",
    email: "stpierre.kolda@eglise.catho.sn",
    horaires: {
      dimanche: ["07:00","09:00","11:00","18:00"],
      lundi:    ["07:00","18:30"], mardi:    ["07:00","18:30"],
      mercredi: ["07:00","18:30"], jeudi:    ["07:00","18:30"],
      vendredi: ["07:00","18:30"], samedi:   ["07:00","18:30"]
    },
    coordonnees: { lat: 12.8901, lon: -14.4567 },
    curé: "Père Michel Sène"
  },
  {
    id: 7,
    nom: "Église Saint-Michel de Sédhiou",
    ville: "Sédhiou", quartier: "Centre-ville",
    adresse: "Route de Sédhiou",
    telephone: "+221 33 856 78 90",
    email: "stmichel.sedhiou@eglise.catho.sn",
    horaires: {
      dimanche: ["07:00","09:00","11:00","18:00"],
      lundi:    ["07:00","18:30"], mardi:    ["07:00","18:30"],
      mercredi: ["07:00","18:30"], jeudi:    ["07:00","18:30"],
      vendredi: ["07:00","18:30"], samedi:   ["07:00","18:30"]
    },
    coordonnees: { lat: 12.7234, lon: -15.5678 },
    curé: "Père Pierre Diop"
  },
  {
    id: 8,
    nom: "Église Saint-Jean-Baptiste de Kédougou",
    ville: "Kédougou", quartier: "Centre-ville",
    adresse: "Route de Kédougou",
    telephone: "+221 33 845 67 89",
    email: "stjean.kedougou@eglise.catho.sn",
    horaires: {
      dimanche: ["07:00","09:00","11:00","18:00"],
      lundi:    ["07:00","18:30"], mardi:    ["07:00","18:30"],
      mercredi: ["07:00","18:30"], jeudi:    ["07:00","18:30"],
      vendredi: ["07:00","18:30"], samedi:   ["07:00","18:30"]
    },
    coordonnees: { lat: 12.5678, lon: -12.2345 },
    curé: "Père Michel Sarr"
  }
];

// Saints du jour (clé = "mois-jour")
const SAINTS = {
  "1-1": { name: "Sainte Marie, Mère de Dieu", desc: "Mère de Jésus-Christ, figure centrale du christianisme, symbole d'humilité et d'obéissance à Dieu." },
  "1-2": { name: "Saint Basile le Grand", desc: "Évêque et docteur de l'Église, père du monachisme oriental." },
  "1-3": { name: "Sainte Geneviève", desc: "Patronne de Paris, connue pour sa courageuse défense de la ville." },
  "1-4": { name: "Sainte Angèle de Foligno", desc: "Mystique italienne du 13ème siècle, exemple de conversion." },
  "1-5": { name: "Saint Jean Népomucène", desc: "Prêtre martyr tchèque, défenseur du secret de confession." },
  "1-6": { name: "Saint Raphaël Archange", desc: "Archange guérisseur et compagnon des voyageurs." },
  "1-7": { name: "Saint Raymond de Penafort", desc: "Dominicain catalan, grand canoniste et confesseur." },
  "1-8": { name: "Saint Lucien", desc: "Martyr romain, premier évangélisateur de la Gaule." },
  "1-9": { name: "Sainte Apolline", desc: "Vierge et martyre, patronne des dentistes." },
  "1-10": { name: "Saint Guillaume", desc: "Moine fondateur, modèle d'humilité et de travail." },
  "1-11": { name: "Saint Paulin de Nole", desc: "Poète et évêque, père de famille devenu pasteur." },
  "1-12": { name: "Sainte Tatiana", desc: "Martyre romaine, patronne des étudiants russes." },
  "1-13": { name: "Saint Hilaire", desc: "Évêque de Poitiers, docteur de l'Église et défenseur de la Trinité." },
  "1-14": { name: "Sainte Nina", desc: "Apôtre de la Géorgie, évangélisatrice au 4ème siècle." },
  "1-15": { name: "Saint Paul ermite", desc: "Moine égyptien, père du monachisme dans le désert." },
  "1-16": { name: "Saint Marcel", desc: "Évêque de Paris, martyr courageux face aux persécutions." },
  "1-17": { name: "Saint Antoine le Grand", desc: "Père du monachisme, il a vécu dans le désert en Égypte dans la prière et l'ascèse." },
  "1-18": { name: "Sainte Prisca", desc: "Vierge et martyre romaine, exemple de foi précoce." },
  "1-19": { name: "Saint Marius", desc: "Martyr romain avec sa famille, témoin de la foi chrétienne." },
  "1-20": { name: "Saint Sébastien", desc: "Martyr romain, soldat devenu protecteur contre les épidémies." },
  "1-21": { name: "Sainte Agnès", desc: "Vierge martyre à Rome, symbole de pureté et de courage." },
  "1-22": { name: "Saint Vincent", desc: "Diacre espagnol, martyr et patron des vignerons." },
  "1-23": { name: "Saint Ildefonse", desc: "Archevêque de Tolède, grand défenseur de la virginité de Marie." },
  "1-24": { name: "Saint François de Sales", desc: "Évêque de Genève, docteur de l'Église et patron des écrivains." },
  "1-25": { name: "Conversion de Saint Paul", desc: "Apparition du Christ à Paul sur le chemin de Damas." },
  "1-26": { name: "Sainte Paule", desc: "Veuve romaine, mère de Sainte Blandine et modèle de charité." },
  "1-27": { name: "Sainte Angèle Merici", desc: "Fondatrice des Ursulines, pionnière de l'éducation des filles." },
  "1-28": { name: "Saint Thomas d'Aquin", desc: "Docteur angélique, grand théologien et philosophe dominicain." },
  "1-29": { name: "Sainte Gildard", desc: "Religieuse mérovingienne, modèle de vie monastique." },
  "1-30": { name: "Sainte Martine", desc: "Vierge martyre romaine, courageuse face à la persécution." },
  "1-31": { name: "Saint Jean Bosco", desc: "Prêtre italien, fondateur des Salésiens et patron de la jeunesse." },
  "2-1": { name: "Saint Ignace d'Antioche", desc: "Évêque martyr, Père de l'Église et disciple de Jean." },
  "2-2": { name: "Sainte Présentation", desc: "Fête de la présentation de Jésus au Temple." },
  "2-3": { name: "Saint Blaise", desc: "Évêque martyr, patron des malades de la gorge." },
  "2-4": { name: "Sainte Jeanne de France", desc: "Fille de Louis XI, fondatrice de l'ordre de l'Annonciade." },
  "2-5": { name: "Sainte Agathe", desc: "Vierge martyre sicilienne, patronne des nourrices." },
  "2-6": { name: "Saint Paul Miki et compagnons", desc: "Martyrs japonais, premiers témoins de la foi au Japon." },
  "2-7": { name: "Saint Richard", desc: "Père de Sainte Gertrude, modèle de fidélité familiale." },
  "2-8": { name: "Sainte Joséphine Bakhita", desc: "Esclave soudanaise devenue sainte, témoin du pardon." },
  "2-9": { name: "Saint Cyrille et Méthode", desc: "Apôtres des Slaves, créateurs de l'alphabet cyrillique." },
  "2-10": { name: "Sainte Scholastique", desc: "Sœur de Saint Benoît, fondatrice du monachisme féminin." },
  "2-11": { name: "Sainte Appoline", desc: "Vierge et martyre, patronne contre les maux de dents." },
  "2-12": { name: "Sainte Bénédicte", desc: "Religieuse, modèle de vie contemplative et de charité." },
  "2-13": { name: "Sainte Catherine de Ricci", desc: "Dominicaine italienne, grande mystique et stigmatisée." },
  "2-14": { name: "Saint Valentin de Rome", desc: "Prêtre martyr, associé à l'amour et au mariage chrétien." },
  "2-15": { name: "Saint Claude", desc: "Évêque de Besançon, grand pasteur et défenseur de la foi." },
  "2-16": { name: "Sainte Julienne", desc: "Religieuse, fondatrice et modèle de persévérance." },
  "2-17": { name: "Saint Alexis", desc: "Fils de noble romain devenu mendiant par humilité." },
  "2-18": { name: "Sainte Bernadette", desc: "Voyante de Lourdes, humble messagère de la Vierge." },
  "2-19": { name: "Saint Mesrob", desc: "Moine arménien, créateur de l'alphabet arménien." },
  "2-20": { name: "Sainte Marguerite de Cortone", desc: "Pécheresse convertie, modèle de pénitence et de charité." },
  "2-21": { name: "Saint Pierre Damien", desc: "Moine réformateur, cardinal et docteur de l'Église." },
  "2-22": { name: "Sainte Anne", desc: "Mère de la Vierge Marie, grand-mère de Jésus." },
  "2-23": { name: "Saint Polycarpe", desc: "Évêque martyr, disciple de l'apôtre Jean." },
  "2-24": { name: "Sainte Modeste", desc: "Vierge et martyre, exemple de foi et de courage." },
  "2-25": { name: "Sainte Walburge", desc: "Abbesse missionnaire, évangélisatrice de l'Allemagne." },
  "2-26": { name: "Sainte Paule", desc: "Fondatrice de monastère, modèle de vie contemplative." },
  "2-27": { name: "Sainte Honorine", desc: "Vierge martyre, première sainte de Normandie." },
  "2-28": { name: "Saint Romain", desc: "Évêque de Rouen, grand pasteur et défenseur de la foi." },
  "3-1": { name: "Saint Aubin", desc: "Évêque d'Angers, pasteur dévoué aux pauvres." },
  "3-2": { name: "Sainte Agnès", desc: "Vierge martyre, modèle de foi et de pureté." },
  "3-3": { name: "Sainte Catherine de Bologne", desc: "Religieuse italienne, mystique et protectrice des artistes." },
  "3-4": { name: "Saint Casimir", desc: "Prince polonais, modèle de chasteté et de piété." },
  "3-5": { name: "Sainte Théophile", desc: "Vierge et martyre, exemple de foi persévérante." },
  "3-6": { name: "Sainte Colette", desc: "Réformatrice des Clarisses, fondatrice de monastères." },
  "3-7": { name: "Sainte Perpétue et Félicité", desc: "Martyres africaines, mères courageuses pour la foi." },
  "3-8": { name: "Saint Jean de Dieu", desc: "Fondateur des frères hospitaliers, patron des malades." },
  "3-9": { name: "Sainte Françoise Romaine", desc: "Veuve romaine, fondatrice des Oblates de Marie." },
  "3-10": { name: "Sainte Anastasie", desc: "Martyre romaine, protectrice contre les poisons." },
  "3-11": { name: "Sainte Eulalie", desc: "Vierge martyre de Barcelone, exemple de courage." },
  "3-12": { name: "Sainte Justine", desc: "Vierge martyre, patronne de la ville de Padoue." },
  "3-13": { name: "Sainte Rodolphe", desc: "Religieuse, modèle de vie monastique et de prière." },
  "3-14": { name: "Sainte Mathilde", desc: "Reine de Germanie, mère de saints et patronne des familles." },
  "3-15": { name: "Sainte Louise de Marillac", desc: "Fondatrice des Filles de la Charité, patronne des travailleurs sociaux." },
  "3-16": { name: "Sainte Bénédicte", desc: "Religieuse, modèle de vie contemplative et d'obéissance." },
  "3-17": { name: "Saint Patrice", desc: "Évêque missionnaire, patron de l'Irlande." },
  "3-18": { name: "Saint Cyrille de Jérusalem", desc: "Docteur de l'Église, grand catéchiste." },
  "3-19": { name: "Saint Joseph", desc: "Protecteur de la Sainte Famille, modèle de travail et de foi." },
  "3-20": { name: "Sainte Clémence", desc: "Vierge et martyre, exemple de foi et de courage." },
  "3-21": { name: "Sainte Léa", desc: "Romaine convertie, modèle de vie monastique." },
  "3-22": { name: "Sainte Léa", desc: "Veuve romaine, mère de Sainte Hélène." },
  "3-23": { name: "Sainte Reine", desc: "Vierge martyre, patronne de la Champagne." },
  "3-24": { name: "Sainte Catherine de Suède", desc: "Mystique et mère de Sainte Brigitte." },
  "3-25": { name: "Annonciation", desc: "Ange Gabriel annonce à Marie qu'elle sera mère de Dieu." },
  "3-26": { name: "Sainte Ludger", desc: "Missionnaire en Allemagne, premier évêque de Münster." },
  "3-27": { name: "Sainte Habiba", desc: "Vierge martyre égyptienne, exemple de foi." },
  "3-28": { name: "Sainte Gontran", desc: "Roi de Bourgogne, modèle de justice et de charité." },
  "3-29": { name: "Sainte Gwladys", desc: "Princesse galloise, mère de saints et modèle de piété." },
  "3-30": { name: "Sainte Marie", desc: "Vierge et martyre, exemple de foi et de courage." },
  "3-31": { name: "Sainte Benjamin", desc: "Diacre martyr, défenseur de la foi chrétienne." },
  "4-1": { name: "Saint Hugues de Grenoble", desc: "Évêque réformateur, connu pour sa vie de prière et de rigueur." },
  "4-2": { name: "Saint François de Paule", desc: "Fondateur d'ordre, homme de pénitence et de foi." },
  "4-3": { name: "Saint Richard de Chichester", desc: "Pasteur dévoué, défenseur de la justice." },
  "4-4": { name: "Saint Isidore de Séville", desc: "Savant et écrivain influent du Moyen Âge." },
  "4-5": { name: "Saint Vincent Ferrier", desc: "Missionnaire célèbre pour ses prédications." },
  "4-6": { name: "Saint Marcellin", desc: "Chrétien ayant donné sa vie pour sa foi." },
  "4-7": { name: "Saint Jean-Baptiste de La Salle", desc: "Fondateur dédié à l'éducation des jeunes." },
  "4-8": { name: "Sainte Julie Billiart", desc: "Fondatrice des Sœurs de Notre-Dame, éducatrice dévouée." },
  "4-9": { name: "Sainte Catherine", desc: "Vierge et martyre, patronne des philosophes." },
  "4-10": { name: "Sainte Madeleine", desc: "Compagne de Jésus, témoin de sa résurrection." },
  "4-11": { name: "Saint Stanislas", desc: "Évêque martyr, patron de la Pologne." },
  "4-12": { name: "Sainte Jules I", desc: "Pape martyr, défenseur de la foi orthodoxe." },
  "4-13": { name: "Sainte Hermine", desc: "Vierge martyre, exemple de foi et de courage." },
  "4-14": { name: "Sainte Lidwine", desc: "Mystique hollandaise, modèle de souffrance offerte." },
  "4-15": { name: "Sainte Patrice", desc: "Vierge martyre, patronne des malades." },
  "4-16": { name: "Sainte Bernadette", desc: "Fille de bergers, messagère de la Vierge à Lourdes." },
  "4-17": { name: "Sainte Kateri Tekakwitha", desc: "Première sainte amérindienne, vierge et mystique." },
  "4-18": { name: "Sainte Parfait", desc: "Vierge martyre, exemple de foi et de courage." },
  "4-19": { name: "Sainte Léopoldine", desc: "Vierge martyre, patronne des jeunes filles." },
  "4-20": { name: "Sainte Odile", desc: "Patronne de l'Alsace, aveugle guérie par la foi." },
  "4-21": { name: "Saint Anselme de Cantorbéry", desc: "Philosophe et archevêque, célèbre pour ses réflexions sur la foi et la raison." },
  "4-22": { name: "Sainte Léa", desc: "Veuve romaine, modèle de vie monastique." },
  "4-23": { name: "Saint Georges", desc: "Martyr et soldat, patron de l'Angleterre et de la Géorgie." },
  "4-24": { name: "Sainte Fidèle", desc: "Vierge martyre, exemple de foi et de courage." },
  "4-25": { name: "Saint Marc", desc: "Auteur d'un des quatre Évangiles, témoin de la vie de Jésus." },
  "4-26": { name: "Sainte Alda", desc: "Religieuse, modèle de foi et de patience." },
  "4-27": { name: "Sainte Zita", desc: "Servante modèle de simplicité et de charité." },
  "4-28": { name: "Sainte Valérie", desc: "Vierge martyre, patronne des malades." },
  "4-29": { name: "Sainte Catherine de Sienne", desc: "Docteur de l'Église, mystique et diplomate." },
  "4-30": { name: "Saint Jacques le Majeur", desc: "Apôtre, premier évêque de Jérusalem." },
  "5-1": { name: "Saint Joseph artisan", desc: "Version de Saint Joseph célébrée comme modèle des travailleurs." },
  "5-2": { name: "Saint Athanase d'Alexandrie", desc: "Docteur de l'Église, défenseur de la divinité du Christ." },
  "5-3": { name: "Sainte Marie", desc: "Vierge et martyre, exemple de foi et de courage." },
  "5-4": { name: "Sainte Monique", desc: "Mère de Saint Augustin, modèle de prière persévérante." },
  "5-5": { name: "Sainte Angèle", desc: "Vierge et martyre, patronne des jeunes filles." },
  "5-6": { name: "Sainte Éphrem", desc: "Diacre et docteur de l'Église, grand poète chrétien." },
  "5-7": { name: "Sainte Rosa", desc: "Vierge et martyre, exemple de foi et de courage." },
  "5-8": { name: "Sainte Appoline", desc: "Vierge martyre, patronne des dentistes." },
  "5-9": { name: "Saint Pacôme", desc: "Pionnier de la vie monastique en communauté." },
  "5-10": { name: "Sainte Solange", desc: "Jeune fille morte pour sa foi." },
  "5-11": { name: "Sainte Estelle", desc: "Connue pour sa foi et sa simplicité." },
  "5-12": { name: "Saint Pancrace", desc: "Jeune chrétien fidèle jusqu'à la mort." },
  "5-13": { name: "Notre-Dame de Fatima", desc: "Commémoration des apparitions de la Vierge au Portugal." },
  "5-14": { name: "Saint Matthias", desc: "Choisi pour remplacer Judas parmi les apôtres." },
  "5-15": { name: "Sainte Denise", desc: "Jeune chrétienne morte pour sa foi." },
  "5-16": { name: "Saint Honoré d'Amiens", desc: "Connu pour sa bonté et sa générosité." },
  "5-17": { name: "Saint Pascal Baylon", desc: "Dévot à l'Eucharistie." },
  "5-18": { name: "Saint Jean I", desc: "Pape mort en exil pour sa foi." },
  "5-19": { name: "Saint Yves Hélory", desc: "Patron des juristes, défenseur des pauvres." },
  "5-20": { name: "Saint Bernardin de Sienne", desc: "Grand prédicateur populaire." },
  "5-21": { name: "Saint Constantin", desc: "Empereur ayant favorisé le christianisme." },
  "5-22": { name: "Sainte Rita de Cascia", desc: "Sainte des causes difficiles." },
  "5-23": { name: "Saint Didier", desc: "Pasteur fidèle à sa mission." },
  "5-24": { name: "Saint Donatien et Rogatien", desc: "Deux frères morts pour leur foi." },
  "5-25": { name: "Saint Bède le Vénérable", desc: "Historien et moine érudit." },
  "5-26": { name: "Saint Philippe Néri", desc: "Apôtre de la joie et de la charité." },
  "5-27": { name: "Saint Augustin de Cantorbéry", desc: "Évangélisateur de l'Angleterre." },
  "5-28": { name: "Saint Germain de Paris", desc: "Pasteur attentif aux pauvres." },
  "5-29": { name: "Sainte Aymard", desc: "Moine engagé dans la vie spirituelle." },
  "5-30": { name: "Sainte Jeanne d'Arc", desc: "Héroïne guidée par sa foi." },
  "5-31": { name: "Visitation de Marie", desc: "Rencontre entre Marie et Élisabeth." },
  "6-1": { name: "Saint Justin", desc: "Philosophe converti, il a défendu la foi chrétienne." },
  "6-2": { name: "Sainte Blandine", desc: "Jeune chrétienne courageuse face aux persécutions." },
  "6-3": { name: "Saint Charles Lwanga et ses compagnons", desc: "Martyrs africains restés fidèles à leur foi." },
  "6-4": { name: "Sainte Clotilde", desc: "Reine chrétienne ayant favorisé la conversion de son peuple." },
  "6-5": { name: "Saint Boniface", desc: "Missionnaire en Allemagne, mort pour sa foi." },
  "6-6": { name: "Saint Norbert", desc: "Fondateur d'ordre et réformateur de l'Église." },
  "6-7": { name: "Saint Robert", desc: "Fondateur d'abbaye et homme de prière." },
  "6-8": { name: "Saint Médard", desc: "Connu pour sa bonté et sa générosité." },
  "6-9": { name: "Sainte Colomba", desc: "Religieuse engagée dans la vie monastique." },
  "6-10": { name: "Saint Landry", desc: "Fondateur d'hôpitaux pour les pauvres." },
  "6-11": { name: "Saint Barnabé", desc: "Compagnon de saint Paul dans la mission." },
  "6-12": { name: "Saint Guy", desc: "Homme de prière vivant retiré du monde." },
  "6-13": { name: "Saint Antoine de Padoue", desc: "Prédicateur célèbre et docteur de l'Église." },
  "6-14": { name: "Saint Élisée", desc: "Prophète de l'Ancien Testament." },
  "6-15": { name: "Sainte Germaine de Pibrac", desc: "Jeune bergère connue pour sa foi." },
  "6-16": { name: "Saint Jean-François Régis", desc: "Missionnaire auprès des pauvres." },
  "6-17": { name: "Saint Hervé", desc: "Saint aveugle connu pour sa foi." },
  "6-18": { name: "Saint Léonce", desc: "Chrétien mort pour sa foi." },
  "6-19": { name: "Saint Romuald", desc: "Fondateur d'un ordre monastique." },
  "6-20": { name: "Saint Silvère", desc: "Pape des premiers siècles de l'Église." },
  "6-21": { name: "Saint Aloys Gonzague", desc: "Jeune saint connu pour sa pureté." },
  "6-22": { name: "Saint Paulin de Nole", desc: "Poète et évêque engagé." },
  "6-23": { name: "Sainte Audrey", desc: "Religieuse fondatrice d'abbaye." },
  "6-24": { name: "Saint Jean-Baptiste", desc: "Il a baptisé Jésus et annoncé sa venue." },
  "6-25": { name: "Saint Prosper", desc: "Théologien et défenseur de la foi." },
  "6-26": { name: "Saint Anthelme", desc: "Pasteur dévoué et réformateur." },
  "6-27": { name: "Saint Cyrille d'Alexandrie", desc: "Grand théologien des premiers siècles." },
  "6-28": { name: "Saint Irénée de Lyon", desc: "Défenseur de la doctrine chrétienne." },
  "6-29": { name: "Saints Pierre et Paul", desc: "Deux grandes figures fondatrices de l'Église." },
  "6-30": { name: "Saints Premiers martyrs de Rome", desc: "Premiers chrétiens morts pour leur foi à Rome." },
  "7-1": { name: "Saint Thierry", desc: "Pasteur dévoué, connu pour sa vie de foi." },
  "7-2": { name: "Saint Martinien", desc: "Chrétien ayant souffert pour sa foi." },
  "7-3": { name: "Saint Thomas", desc: "Apôtre qui proclame la foi après avoir douté." },
  "7-4": { name: "Saint Florent", desc: "Pasteur attentif à sa communauté." },
  "7-5": { name: "Saint Antoine-Marie Zaccaria", desc: "Fondateur engagé dans la réforme spirituelle." },
  "7-6": { name: "Sainte Maria Goretti", desc: "Jeune fille symbole de pureté et de pardon." },
  "7-7": { name: "Saint Raoul", desc: "Moine engagé dans la vie spirituelle." },
  "7-8": { name: "Saint Thibault", desc: "Chrétien fidèle face aux persécutions." },
  "7-9": { name: "Saint Augustin Zhao Rong et ses compagnons", desc: "Martyrs ayant témoigné de leur foi en Chine." },
  "7-10": { name: "Saint Ulrich d'Augsbourg", desc: "Pasteur courageux face aux difficultés." },
  "7-11": { name: "Saint Benoît", desc: "Fondateur du monachisme occidental." },
  "7-12": { name: "Saint Olivier", desc: "Chrétien mort pour sa foi." },
  "7-13": { name: "Saint Henri", desc: "Dirigeant chrétien engagé pour la foi." },
  "7-14": { name: "Saint Camille de Lellis", desc: "Fondateur d'hôpitaux pour les pauvres." },
  "7-15": { name: "Saint Bonaventure", desc: "Théologien franciscain et docteur de l'Église." },
  "7-16": { name: "Notre-Dame du Mont Carmel", desc: "Apparition de la Vierge Marie au Carmel." },
  "7-17": { name: "Sainte Charlotte", desc: "Connue pour sa foi et sa simplicité." },
  "7-18": { name: "Saint Frédéric", desc: "Dirigeant juste et protecteur des pauvres." },
  "7-19": { name: "Saint Arsène", desc: "Moine engagé dans la vie spirituelle." },
  "7-20": { name: "Saint Apollinaire", desc: "Évêque et théologien des premiers siècles." },
  "7-21": { name: "Saint Laurent de Brindisi", desc: "Grand prédicateur et défenseur de la foi." },
  "7-22": { name: "Sainte Marie-Madeleine", desc: "Première témoin de la résurrection du Christ." },
  "7-23": { name: "Sainte Brigitte de Suède", desc: "Mystique et fondatrice d'ordre religieux." },
  "7-24": { name: "Sainte Christine", desc: "Jeune chrétienne morte pour sa foi." },
  "7-25": { name: "Saint Jacques", desc: "Apôtre et premier martyr parmi les Douze." },
  "7-26": { name: "Sainte Anne et Joachim", desc: "Parents de la Vierge Marie, modèles de foi." },
  "7-27": { name: "Sainte Nathalie", desc: "Chrétienne fidèle face aux persécutions." },
  "7-28": { name: "Saint Samson", desc: "Juge hébreu connu pour sa force et sa foi." },
  "7-29": { name: "Sainte Marthe", desc: "Sœur de Lazare, femme de foi et d'accueil." },
  "7-30": { name: "Saint Pierre Chrysologue", desc: "Prédicateur reconnu pour son éloquence." },
  "7-31": { name: "Saint Ignace de Loyola", desc: "Fondateur des Jésuites, modèle de discipline." },
  "8-1": { name: "Saint Alphonse de Liguori", desc: "Évêque et docteur de l'Église, fondateur des Rédemptoristes, grand théologien de la morale chrétienne." },
  "8-2": { name: "Saint Eusèbe de Verceil", desc: "Évêque qui défendit la foi catholique contre l'arianisme au 4ème siècle." },
  "8-4": { name: "Saint Jean-Marie Vianney", desc: "Curé d'Ars, patron des curés du monde entier, connu pour ses longues heures au confessionnal." },
  "8-6": { name: "Transfiguration du Seigneur", desc: "Fête où Jésus se révèle dans sa gloire divine devant Pierre, Jacques et Jean sur la montagne." },
  "8-8": { name: "Saint Dominique", desc: "Fondateur de l'Ordre des Prêcheurs (Dominicains), grand défenseur de la foi et prédicateur infatigable." },
  "8-10": { name: "Saint Laurent", desc: "Diacre et martyr romain, connu pour son courage face à la mort et sa charité envers les pauvres." },
  "8-11": { name: "Sainte Claire d'Assise", desc: "Fondatrice des Clarisses, amie de Saint François, modèle de pauvreté et de contemplation." },
  "8-12": { name: "Sainte Jeanne de Chantal", desc: "Fondatrice de l'Ordre de la Visitation avec Saint François de Sales, veuve et mystique." },
  "8-13": { name: "Saints Pontien et Hippolyte", desc: "Pape et prêtre martyrs, réconciliés dans la foi avant leur mort en Sardaigne." },
  "8-14": { name: "Saint Maximilien Kolbe", desc: "Prêtre franciscain polonais mort à Auschwitz en se substituant à un père de famille." },
  "8-15": { name: "Assomption de Marie", desc: "Marie élevée au ciel corps et âme, fête majeure de l'Église catholique." },
  "8-16": { name: "Saint Étienne de Hongrie", desc: "Premier roi chrétien de Hongrie, évangélisateur de son peuple au 11ème siècle." },
  "8-19": { name: "Saint Jean-Eudes", desc: "Prêtre normand fondateur des Eudistes, apôtre des cœurs de Jésus et Marie." },
  "8-20": { name: "Saint Bernard de Clairvaux", desc: "Moine cistercien, docteur de l'Église, grande figure spirituelle du Moyen Âge." },
  "8-21": { name: "Saint Pie X", desc: "Pape qui encouragea la communion fréquente et lutta contre le modernisme, canonisé en 1954." },
  "8-22": { name: "Marie Reine", desc: "Fête célébrant la royauté de Marie sur toute la création, proclamée par Pie XII en 1954." },
  "8-23": { name: "Sainte Rose de Lima", desc: "Première sainte des Amériques, mystique dominicaine péruvienne du 17ème siècle." },
  "8-24": { name: "Saint Barthélemy", desc: "Apôtre de Jésus, évangélisateur de l'Inde et de l'Arménie, martyr écorché vif." },
  "8-25": { name: "Saint Louis IX", desc: "Roi de France, modèle de justice et de charité, mort lors d'une croisade à Tunis." },
  "8-27": { name: "Sainte Monique", desc: "Mère de Saint Augustin, modèle de persévérance dans la prière pour la conversion de son fils." },
  "8-28": { name: "Saint Augustin", desc: "Évêque d'Hippone, docteur de la grâce, auteur des Confessions et de la Cité de Dieu." },
  "8-29": { name: "Martyre de Saint Jean-Baptiste", desc: "Décapité sur ordre d'Hérode à la demande de Salomé." },
  "9-1": { name: "Saint Grégoire le Grand", desc: "Pape et docteur de l'Église, réformateur de la liturgie, fondateur du chant grégorien." },
  "9-8": { name: "Nativité de Marie", desc: "Fête de la naissance de la Vierge Marie, mère de Jésus." },
  "9-9": { name: "Saint Pierre Claver", desc: "Jésuite espagnol qui consacra sa vie au service des esclaves africains à Carthagène." },
  "9-13": { name: "Saint Jean Chrysostome", desc: "Archevêque de Constantinople, docteur de l'Église, grand prédicateur de l'Antiquité." },
  "9-14": { name: "Exaltation de la Sainte Croix", desc: "Fête célébrant la croix comme signe de salut et de victoire sur la mort." },
  "9-15": { name: "Notre-Dame des Douleurs", desc: "Mémoire des souffrances de Marie au pied de la croix de son fils Jésus." },
  "9-16": { name: "Saints Corneille et Cyprien", desc: "Pape et évêque martyrs, tous deux morts pour leur foi au 3ème siècle." },
  "9-17": { name: "Saint Robert Bellarmin", desc: "Jésuite et cardinal, docteur de l'Église, grand défenseur du catholicisme face au protestantisme." },
  "9-19": { name: "Saint Janvier", desc: "Évêque et martyr, patron de Naples, dont le sang se liquéfie miraculeusement chaque année." },
  "9-20": { name: "Saints André Kim et Paul Chong", desc: "Premiers martyrs coréens, morts pour leur foi au 19ème siècle." },
  "9-21": { name: "Saint Matthieu", desc: "Apôtre et évangéliste, ancien collecteur d'impôts converti par l'appel de Jésus." },
  "9-23": { name: "Saint Padre Pio", desc: "Capucin stigmatisé, grand confesseur et mystique italien du 20ème siècle." },
  "9-26": { name: "Saints Côme et Damien", desc: "Médecins jumeaux martyrs, patrons des médecins et pharmaciens chrétiens." },
  "9-27": { name: "Saint Vincent de Paul", desc: "Prêtre français fondateur des Lazaristes et des Filles de la Charité, apôtre des pauvres." },
  "9-28": { name: "Saint Wenceslas", desc: "Duc de Bohême martyr, patron de la République tchèque, assassiné par son frère." },
  "9-29": { name: "Saints Michel, Gabriel et Raphaël", desc: "Les trois archanges, messagers et serviteurs de Dieu mentionnés dans la Bible." },
  "9-30": { name: "Saint Jérôme", desc: "Docteur de l'Église, traducteur de la Bible en latin (Vulgate), ermite et grand érudit." },
  "10-1": { name: "Sainte Thérèse de l'Enfant-Jésus", desc: "Carmélite de Lisieux, docteur de l'Église, patronne des missions avec sa petite voie." },
  "10-2": { name: "Saints Anges Gardiens", desc: "Fête des anges que Dieu confie à chaque personne pour la guider et la protéger." },
  "10-4": { name: "Saint François d'Assise", desc: "Fondateur des Franciscains, ami des pauvres et des animaux, stigmatisé, patron de l'écologie." },
  "10-6": { name: "Saint Bruno", desc: "Fondateur de l'Ordre des Chartreux, chercheur de Dieu dans le silence et la contemplation." },
  "10-7": { name: "Notre-Dame du Rosaire", desc: "Fête commémorant la victoire de Lépante obtenue par la prière du rosaire en 1571." },
  "10-9": { name: "Saint Denis", desc: "Premier évêque de Paris, martyr décapité sur la butte Montmartre au 3ème siècle." },
  "10-11": { name: "Saint Jean XXIII", desc: "Pape qui convoqua le Concile Vatican II, aimé pour sa bonté et son humanité." },
  "10-15": { name: "Sainte Thérèse d'Avila", desc: "Carmélite réformatrice, docteur de l'Église, grande mystique espagnole du 16ème siècle." },
  "10-16": { name: "Saint Ignace d'Antioche", desc: "Évêque et martyr, Père de l'Église, dévoré par les lions à Rome au 2ème siècle." },
  "10-17": { name: "Saint Ignace d'Antioche", desc: "Évêque martyr et Père de l'Église, auteur de lettres fondamentales pour la foi chrétienne." },
  "10-18": { name: "Saint Luc", desc: "Évangéliste et médecin, compagnon de Saint Paul, auteur de l'Évangile et des Actes des Apôtres." },
  "10-19": { name: "Saint Jean de Brébeuf", desc: "Jésuite français martyrisé par les Iroquois au Canada, patron du Canada." },
  "10-22": { name: "Saint Jean-Paul II", desc: "Pape polonais qui a traversé le monde pour annoncer l'Évangile, canonisé en 2014." },
  "10-23": { name: "Saint Jean de Capistran", desc: "Franciscain et prédicateur, organisateur de la résistance chrétienne contre les Ottomans." },
  "10-24": { name: "Saint Antoine-Marie Claret", desc: "Archevêque espagnol fondateur des Claretains, missionnaire infatigable." },
  "10-28": { name: "Saints Simon et Jude", desc: "Deux apôtres de Jésus, évangélisateurs de Perse où ils moururent martyrs." },
  "11-1": { name: "Toussaint", desc: "Célébration de tous les saints connus et inconnus qui jouissent de la gloire du paradis." },
  "11-2": { name: "Commémoration des fidèles défunts", desc: "Prière de l'Église pour tous les fidèles décédés qui attendent la gloire de Dieu." },
  "11-3": { name: "Saint Martin de Porrès", desc: "Frère dominicain péruvien métis, humble serviteur des pauvres et des malades." },
  "11-4": { name: "Saint Charles Borromée", desc: "Archevêque de Milan, grand réformateur de l'Église après le Concile de Trente." },
  "11-9": { name: "Dédicace de la Basilique du Latran", desc: "Fête de la cathédrale du pape à Rome, mère de toutes les églises." },
  "11-10": { name: "Saint Léon le Grand", desc: "Pape et docteur de l'Église, défenseur de Rome contre Attila, grand théologien." },
  "11-11": { name: "Saint Martin de Tours", desc: "Évêque qui partagea son manteau avec un pauvre, patron de la France et des soldats." },
  "11-12": { name: "Saint Josaphat", desc: "Archevêque ukrainien martyr, mort pour l'union des chrétiens d'Orient et d'Occident." },
  "11-15": { name: "Saint Albert le Grand", desc: "Dominicain allemand, docteur de l'Église, maître de Saint Thomas d'Aquin." },
  "11-16": { name: "Sainte Marguerite d'Écosse", desc: "Reine d'Écosse, modèle de charité et de piété, réformatrice de l'Église écossaise." },
  "11-17": { name: "Sainte Élisabeth de Hongrie", desc: "Princesse qui consacra sa vie aux pauvres et aux malades après la mort de son mari." },
  "11-18": { name: "Dédicace des basiliques de Pierre et Paul", desc: "Fête des deux grandes basiliques apostoliques de Rome." },
  "11-21": { name: "Présentation de Marie", desc: "Fête de la présentation de la Vierge Marie au Temple de Jérusalem dans son enfance." },
  "11-22": { name: "Sainte Cécile", desc: "Vierge et martyre romaine, patronne des musiciens et de la musique sacrée." },
  "11-23": { name: "Saint Clément Ier", desc: "Troisième successeur de Pierre, pape et martyr, auteur d'une importante lettre aux Corinthiens." },
  "11-24": { name: "Saints André Dũng-Lạc et compagnons", desc: "117 martyrs vietnamiens morts pour leur foi entre le 17ème et 19ème siècle." },
  "11-25": { name: "Sainte Catherine d'Alexandrie", desc: "Vierge et martyre, patronne des philosophes et des étudiants, morte roue et épée." },
  "11-30": { name: "Saint André", desc: "Premier apôtre appelé par Jésus, frère de Pierre, crucifié sur une croix en X en Grèce." },
  "12-3": { name: "Saint François Xavier", desc: "Jésuite co-fondateur avec Ignace, grand missionnaire en Inde et au Japon, apôtre de l'Asie." },
  "12-4": { name: "Saint Jean de Damas", desc: "Moine et docteur de l'Église, défenseur des icônes, grand théologien de l'Orient chrétien." },
  "12-6": { name: "Saint Nicolas de Myre", desc: "Évêque généreux de Turquie, patron des enfants, des marins et des pauvres, inspirateur du Père Noël." },
  "12-7": { name: "Saint Ambroise", desc: "Évêque de Milan, docteur de l'Église, qui baptisa Saint Augustin et résista aux empereurs." },
  "12-8": { name: "Immaculée Conception", desc: "Marie conçue sans péché originel, pleine de grâce dès le premier instant de sa vie." },
  "12-9": { name: "Saint Juan Diego", desc: "Indien mexicain à qui la Vierge de Guadalupe apparut en 1531, premier saint amérindien." },
  "12-10": { name: "Notre-Dame de Lorette", desc: "Vénération de la maison de Nazareth où vécut la Sainte Famille, transportée miraculeusement." },
  "12-11": { name: "Saint Damase Ier", desc: "Pape qui confia à Saint Jérôme la traduction de la Bible en latin et défendit l'orthodoxie." },
  "12-12": { name: "Notre-Dame de Guadalupe", desc: "Apparition de la Vierge à Juan Diego au Mexique, patronne des Amériques." },
  "12-13": { name: "Sainte Lucie", desc: "Vierge et martyre sicilienne, dont le nom évoque la lumière, patronne des aveugles et des couturières." },
  "12-14": { name: "Saint Jean de la Croix", desc: "Carme réformateur, docteur de l'Église, grand mystique espagnol, auteur de la Nuit obscure." },
  "12-21": { name: "Saint Pierre Canisius", desc: "Jésuite allemand, docteur de l'Église, apôtre de la Contre-Réforme en Allemagne." },
  "12-23": { name: "Saint Jean de Kęty", desc: "Prêtre polonais professeur de théologie, connu pour sa charité envers les pauvres et les étudiants." },
  "12-25": { name: "Jésus-Christ", desc: "Fête de la naissance de Jésus." },
  "12-26": { name: "Saint Étienne", desc: "Premier martyr chrétien, lapidé à Jérusalem, dont la mort fut témoin par le jeune Saul de Tarse." },
  "12-27": { name: "Saint Jean l'Évangéliste", desc: "Apôtre bien-aimé de Jésus, auteur du quatrième évangile et de l'Apocalypse." },
  "12-28": { name: "Saints Innocents", desc: "Enfants massacrés par Hérode cherchant à tuer l'enfant Jésus, premiers martyrs involontaires." },
  "12-29": { name: "Saint Thomas Becket", desc: "Archevêque de Canterbury assassiné dans sa cathédrale pour avoir défendu l'Église face au roi." },
  "12-31": { name: "Saint Sylvestre Ier", desc: "Pape sous le règne de Constantin, qui vit la reconnaissance officielle du christianisme dans l'Empire romain." }
};

// Fêtes liturgiques 2026
const FEASTS_2026 = [
  { name: "Épiphanie",           date: new Date(2026,  0,  6), desc: "Manifestation du Christ aux nations, visite des mages." },
  { name: "Cendres",             date: new Date(2026,  1, 18), desc: "Début du Carême, appel à la conversion et à la prière." },
  { name: "Rameaux",             date: new Date(2026,  3,  5), desc: "Entrée triomphale de Jésus à Jérusalem." },
  { name: "Pâques",              date: new Date(2026,  3,  6), desc: "Résurrection du Christ, victoire sur la mort." },
  { name: "Ascension",           date: new Date(2026,  4, 15), desc: "Élévation du Christ au ciel 40 jours après Pâques." },
  { name: "Pentecôte",           date: new Date(2026,  4, 25), desc: "Don du Saint-Esprit, naissance de l'Église." },
  { name: "Fête-Dieu",           date: new Date(2026,  5,  9), desc: "Fête du Saint-Sacrement, présence réelle du Christ." },
  { name: "Saint Pierre et Paul",date: new Date(2026,  6, 29), desc: "Fête des deux grands apôtres, fondements de l'Église." },
  { name: "Assomption",          date: new Date(2026,  7, 15), desc: "Marie élevée au ciel corps et âme." },
  { name: "Toussaint",           date: new Date(2026, 10,  1), desc: "Fête de tous les saints du paradis." },
  { name: "Immaculée Conception",date: new Date(2026, 11,  8), desc: "Marie conçue sans péché originel." },
  { name: "Noël",                date: new Date(2026, 11, 25), desc: "Naissance de Jésus Christ, Fils de Dieu fait homme." }
];

// Traduction des jours
const JOURS_FR = {
  dimanche: "Dimanche", lundi: "Lundi",   mardi: "Mardi",
  mercredi: "Mercredi", jeudi: "Jeudi",   vendredi: "Vendredi",
  samedi:   "Samedi"
};

// Fonctions utilitaires sur les données

/** Retourne le saint du jour (ou un saint générique). */
function getSaint() {
  const today = new Date();
  const key   = `${today.getMonth() + 1}-${today.getDate()}`;
  return SAINTS[key] || { name: "Saint du jour", desc: "Un saint de l'Église nous inspire par sa foi et son témoignage." };
}

/** Retourne la prochaine fête liturgique à venir. */
function getNextFeast() {
  const now = new Date();
  now.setHours(0, 0, 0, 0);
  const found = FEASTS_2026.find(f => {
    const d = new Date(f.date);
    d.setHours(0, 0, 0, 0);
    return d >= now;
  });
  return found || FEASTS_2026[FEASTS_2026.length - 1];
}

/** Retourne "Aujourd'hui", "Demain", "Dans N jours" ou "Passé". */
function daysUntil(date) {
  const now  = new Date(); now.setHours(0, 0, 0, 0);
  const d    = new Date(date); d.setHours(0, 0, 0, 0);
  const diff = Math.round((d - now) / 86400000);
  if (diff === 0) return "Aujourd'hui";
  if (diff === 1) return "Demain";
  if (diff  < 0) return "Passé";
  return `Dans ${diff} jours`;
}

/** Formate une date en français : "22 avril 2026". */
function formatDate(date) {
  return date.toLocaleDateString("fr-FR", { day: "numeric", month: "long", year: "numeric" });
}

/** Filtre les paroisses selon le texte de recherche stocké dans le state. */
function getFiltered() {
  if (!state.search.trim()) return PAROISSES;
  const q = state.search.toLowerCase();
  return PAROISSES.filter(p =>
    p.nom.toLowerCase().includes(q)      ||
    p.ville.toLowerCase().includes(q)    ||
    p.quartier.toLowerCase().includes(q) ||
    (p.curé && p.curé.toLowerCase().includes(q))
  );
}